travis:
  secure:
    BINSTAR_TOKEN: mq5THstpVr5EjifKeBxLPCMJc785AahDqkR5wK1XA/kuN0hEaEHuTPytRBCQgfheVpBxmnhe4k/morxt4NgGplKfuTem0PeAb0rdFLTHQLGWTsTV88kE/y3aRCTapZvL8YC8CgMRZ8PCzmDiV7yKorryOe6Wc4E8xETkBWcZ6QctYEGl5AwZigfssPZXhXgKpVwNB7n2wJCcKBqdDkbvpFNQ1sr1tR9y0pLgStp21H2V0agNY+xhwsUdmezJ3Qnac4fzLDtgmb8coWNOvO7EvfsE9rccJJy1k2tV1GywUTjWethjo0lqMjUdi3oWKq+Mui/RgVifsjuCpRJjL/KkbEPaQ2eZtbfjIvQWNC0IZHunK19lGVGEul3Gg4peEwMIdaDq0L6XZVJW15iBQLA/Vb/BCYYHR0DKAUvBsfxuwe9eGUqnqXElrmh5yEWBCz3Ndz4Hd1xi1F+QIKd96KitGXsCJDcOY1vCtJOlJ5vZoMu/ifpJh9HXUPMjtjBb2PYrELlNVpmAIlwgOMdv6jPQZ97NZBSu7fs0qu/IZghCHdZ9I89aszvpynpRGlalhI/O0+K8hHZEmxnxQh/v5YjgzJckfM3UKYYDKuqEkk+VW0v5yhOpvyQh2jbw47NzGGSSWjkSkQEDTHrurUoGVtxIwj1n2l7gjbb2670285jiloA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
